Algoritmo "Primeiro"
   // Disciplina  :  [Linguagem e Lógica de Programação]
   // Professor   : Gustavo Guanabara
   // Descrição   : 1° Código Feito no Curso
   // Autor(a)    : Davi C. Menez
   // Data atual  : 26/01/2021

Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    ESCREVAL("Olá, Mundo!")
    ESCREVA("Me livrei da maldição!")

Fimalgoritmo